<?php
$item_list = array(


    array("title" => "男·全网大热榜", "input" => "https://contentxs.pysmei.com/top/man/top/hot/week"),
    array("title" => "男·超人气精品", "input" => "https://contentxs.pysmei.com/top/man/top/vote/week"),
    array("title" => "女·全网大热榜", "input" => "https://contentxs.pysmei.com/top/lady/top/hot/week"),
    array("title" => "女·超人气精品", "input" => "https://contentxs.pysmei.com/top/lady/top/vote/week"),
    array("title" => "玄幻奇幻", "input" => "https://contentxs.pysmei.com/Categories/1/hot/"),
    array("title" => "武侠仙侠", "input" => "https://contentxs.pysmei.com/Categories/2/hot/"),
    array("title" => "都市言情", "input" => "https://contentxs.pysmei.com/Categories/3/hot/"),
    array("title" => "历史军事", "input" => "https://contentxs.pysmei.com/Categories/4/hot/"),
    array("title" => "科幻灵异", "input" => "https://contentxs.pysmei.com/Categories/5/hot/"),
    array("title" => "网游竞技", "input" => "https://contentxs.pysmei.com/Categories/6/hot/"),
    array("title" => "女生频道", "input" => "https://contentxs.pysmei.com/Categories/7/hot/"),
    array("title" => "小说同人", "input" => "https://contentxs.pysmei.com/Categories/66/hot/"),
    array("title" => "玄幻奇幻", "input" => "https://contentxs.pysmei.com/Categories/1/over/"),
    array("title" => "武侠仙侠", "input" => "https://contentxs.pysmei.com/Categories/2/over/"),
    array("title" => "都市言情", "input" => "https://contentxs.pysmei.com/Categories/3/over/"),
    array("title" => "历史军事", "input" => "https://contentxs.pysmei.com/Categories/4/over/"),
    array("title" => "科幻灵异", "input" => "https://contentxs.pysmei.com/Categories/5/over/"),
    array("title" => "网游竞技", "input" => "https://contentxs.pysmei.com/Categories/6/over/"),
    array("title" => "女生频道", "input" => "https://contentxs.pysmei.com/Categories/7/over/"),
    array("title" => "小说同人", "input" => "https://contentxs.pysmei.com/Categories/66/over/"),
    array("title" => "玄幻奇幻", "input" => "https://contentxs.pysmei.com/Categories/1/new/"),
    array("title" => "武侠仙侠", "input" => "https://contentxs.pysmei.com/Categories/2/new/"),
    array("title" => "都市言情", "input" => "https://contentxs.pysmei.com/Categories/3/new/"),
    array("title" => "历史军事", "input" => "https://contentxs.pysmei.com/Categories/4/new/"),
    array("title" => "科幻灵异", "input" => "https://contentxs.pysmei.com/Categories/5/new/"),
    array("title" => "网游竞技", "input" => "https://contentxs.pysmei.com/Categories/6/new/"),
    array("title" => "女生频道", "input" => "https://contentxs.pysmei.com/Categories/7/new/"),
    array("title" => "小说同人", "input" => "https://contentxs.pysmei.com/Categories/66/new/"),
    array("title" => "玄幻奇幻", "input" => "https://contentxs.pysmei.com/Categories/1/vote/"),
    array("title" => "武侠仙侠", "input" => "https://contentxs.pysmei.com/Categories/2/vote/"),
    array("title" => "都市言情", "input" => "https://contentxs.pysmei.com/Categories/3/vote/"),
    array("title" => "历史军事", "input" => "https://contentxs.pysmei.com/Categories/4/vote/"),
    array("title" => "科幻灵异", "input" => "https://contentxs.pysmei.com/Categories/5/vote/"),
    array("title" => "网游竞技", "input" => "https://contentxs.pysmei.com/Categories/6/vote/"),
    array("title" => "女生频道", "input" => "https://contentxs.pysmei.com/Categories/7/vote/"),
    array("title" => "小说同人", "input" => "https://contentxs.pysmei.com/Categories/66/vote/"),
    array("title" => "最热榜单", "input" => "https://contentxs.pysmei.com/top/man/top/hot/week/"),
    array("title" => "完结榜单", "input" => "https://contentxs.pysmei.com/top/man/top/over/week/"),
    array("title" => "推荐榜单", "input" => "https://contentxs.pysmei.com/top/man/top/commend/week/"),
    array("title" => "新书榜单", "input" => "https://contentxs.pysmei.com/top/man/top/new/week/"),
    array("title" => "评分榜单", "input" => "https://contentxs.pysmei.com/top/man/top/vote/week/"),
    array("title" => "收藏榜单", "input" => "https://contentxs.pysmei.com/top/man/top/collect/week/"),
    array("title" => "最热榜单", "input" => "https://contentxs.pysmei.com/top/man/top/hot/month/"),
    array("title" => "完结榜单", "input" => "https://contentxs.pysmei.com/top/man/top/over/month/"),
    array("title" => "推荐榜单", "input" => "https://contentxs.pysmei.com/top/man/top/commend/month/"),
    array("title" => "新书榜单", "input" => "https://contentxs.pysmei.com/top/man/top/new/month/"),
    array("title" => "评分榜单", "input" => "https://contentxs.pysmei.com/top/man/top/vote/month/"),
    array("title" => "收藏榜单", "input" => "https://contentxs.pysmei.com/top/man/top/collect/month/"),
    array("title" => "最热榜单", "input" => "https://contentxs.pysmei.com/top/man/top/hot/total/"),
    array("title" => "完结榜单", "input" => "https://contentxs.pysmei.com/top/man/top/over/total/"),
    array("title" => "推荐榜单", "input" => "https://contentxs.pysmei.com/top/man/top/commend/total/"),
    array("title" => "新书榜单", "input" => "https://contentxs.pysmei.com/top/man/top/new/total/"),
    array("title" => "评分榜单", "input" => "https://contentxs.pysmei.com/top/man/top/vote/total/"),
    array("title" => "收藏榜单", "input" => "https://contentxs.pysmei.com/top/man/top/collect/total/"),
    array("title" => "最热榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/hot/week/"),
    array("title" => "完结榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/over/week/"),
    array("title" => "推荐榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/commend/week/"),
    array("title" => "新书榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/new/week/"),
    array("title" => "评分榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/vote/week/"),
    array("title" => "收藏榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/collect/week/"),
    array("title" => "最热榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/hot/month/"),
    array("title" => "完结榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/over/month/"),
    array("title" => "推荐榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/commend/month/"),
    array("title" => "新书榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/new/month/"),
    array("title" => "评分榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/vote/month/"),
    array("title" => "收藏榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/collect/month/"),
    array("title" => "最热榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/hot/total/"),
    array("title" => "完结榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/over/total/"),
    array("title" => "推荐榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/commend/total/"),
    array("title" => "新书榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/new/total/"),
    array("title" => "评分榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/vote/total/"),
    array("title" => "收藏榜单", "input" => "https://contentxs.pysmei.com/top/lady/top/collect/total/"),



);


$json_response = array("data" => array("item_list" => $item_list));
header('Content-Type: application/json');
echo json_encode($json_response);

?>